# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinax < Formula
  desc "Turn any documentation site into a local MCP server."
  homepage "https://github.com/desmondsanctity/pinax"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DesmondSanctity/pinax/releases/download/v0.1.0/pinax_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "19b02288691383d9c7ee8c6f02ca180a1abd73a32a1c386b8809a66fef444dd1"

      define_method(:install) do
        bin.install "pinax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DesmondSanctity/pinax/releases/download/v0.1.0/pinax_0.1.0_Darwin_arm64.tar.gz"
      sha256 "8ae46bac5160191dbc54db68b7acb2ed42767d4a95c376247a64e88c637570fe"

      define_method(:install) do
        bin.install "pinax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DesmondSanctity/pinax/releases/download/v0.1.0/pinax_0.1.0_Linux_x86_64.tar.gz"
      sha256 "56f9d706f72ecd538935c05436149d3babd758831978641836adad5dde5d97cb"
      define_method(:install) do
        bin.install "pinax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DesmondSanctity/pinax/releases/download/v0.1.0/pinax_0.1.0_Linux_arm64.tar.gz"
      sha256 "d962e6d4361779d8d9357254487e83d309a443d04cb000bc91bb6a4ec5923521"
      define_method(:install) do
        bin.install "pinax"
      end
    end
  end

  test do
    system "#{bin}/pinax", "--version"
  end
end
